drapergem/draper

Gemfile, gemfiles/4.0.gemfile, gemfiles/4.1.gemfile, lib/draper/railtie.rb, spec/dummy/spec/decorators/active_model_serializers_spec.rb
The current AMS re-write (which will debut as v0.9.0) has changed how serializers are resolved, and removed the `ArraySerializerSupport` module. This change will ensure Draper properly integrates with both AMS pre-0.9.0, and the future.
I went with the obvious approach, but another option would be to instead test the current loaded version of `active_model_serializers` instead. So, sub out those `if defined?(ActiveModel::ArraySerializerSupport)` checks for something like `Gem.loaded_specs['active_model_serializers'].version.release < Gem::Version.new('0.9')`.
Thoughts?
=> Bring back compatibility with ActiveModel::Serializers

README.md
- In order to use kaminari's helper method `page_entries_info`, you
need to delegate `:entry_name`, `:total_count`, `:offset_value` and
`:last_page?`.
=> Update README, extra kaminari methods delegation.

lib/draper/tasks/test.rake
Prior to Rails 4.2 if you ran `rake test` (which in turn ran `rake test:run`) it would only run tests in specific directories. So if you had a new type of file (such as decorators) you needed to append this rake task to include your new file type.
As of [commit 3b12abb in Rails](https://github.com/rails/rails/commit/3b12abba3c4fa0dbd6e8c92bd68fa433847d142c) this is no longer neccessary. The old `rake test:all` which was more inclusive (ran all tests under the `test/` directory) became `rake test`. The old `rake test` that only ran specific directories was removed.
This commit removes the special addition of running the decorator tests. Without this, running `rake test` will first test the decorators, then it will test all files (including the decorators).
=> Don't auto add test:decorators to test:run

lib/draper/decorator.rb, spec/draper/decorator_spec.rb
I noticed some strangeness with how equality works on decorated objects. This is particularly prevalent when dealing with collections of objects and using methods provided by Enumerable. This is a pull request to try and resolve this, at the moment it is just a failing test.
An easy example:
```ruby
model = Model.first
[model, model].uniq.count => 1
[model.decorate, model.decorate].uniq.count => 2
```
Looking into it in more detail it seems a lot of these methods rely on a combination of ```#eql?``` and ```#hash```. Both of these return unexpected results currently. This caused a lot of confusion since ```#group_by``` on a collection wouldn't group, despite many keys being equal. This is particularly a problem when using decorated associations.
This is shown below:
```ruby …
```
=> Resolving some nuances with equality

lib/draper/factory.rb, spec/draper/factory_spec.rb
Since structs respond to `.first`, Draper thinks they're collections and
always tries to wrap them in CollectionDecorators, which is surprising!
This is similar to the issue and fix in [#259].
=> Decorate structs as singular objects (and not as collections)

lib/draper/automatic_delegation.rb, spec/draper/decorator_spec.rb
This should be a simple and safe way to prevent the issue described in _Pull Request_ #708 .
Decorator classes are used to wrap all sorts of objects of different classes, and right now, delegate methods are added permanently to the original Decorator class, making the code believe that the decorated object can `respond_to?` a lot of things, but when time comes to call the methods, they are not really there, and everything comes crashing down.
Adding delegates to the `singleton_class` should fix the issue, without undesirable side effects.
=> Prevent automatically delegated methods from piling up on Decorator class.

README.md
Quick addition to the readme to explain how to access class methods defined on the decorator when an association with the model has been set up correctly.
=> Extend the "Proxying Class Methods" section

lib/generators/rspec/templates/decorator_spec.rb
When I used the generator I noticed it broke my test suite because it used spec_helper instead of rails_helper
=> Updating generator to work for Rails 4

README.md
Adding how to use a PaginatingDecorator (extending Draper::CollectionDecorator) on a class extending Draper::Decorator to README.md
This explains how to use ArticleDecorator.decorate_collection(@articles.paginate(page: params[:page])) and have your @articles respond to pagination methods whilst individual articles get decorated
=> Adding collection_decorator_class to README.md

README.md
We are currently developing an engine-only style app. To keep things integration tested, we have the entire spec suite being ran as one. It took a while, but I finally found Draper::ViewContext.controller.
Problem:
I was unable to access any of the route helpers that rails provides via the view_context / `h`
```bash
Failure/Error: decorated.form_url
NoMethodError:
undefined method `some_named_path' for #<#<Class:0x007fc891d6e7d0>:0x007fc8a6347b70>
```
Solution:
In an RSpec config block:
```ruby
config.before(:each, type: :decorator) do |example|
Draper::ViewContext.controller = ExampleEngine::CustomRootController.new
end
```
Can optionally add a further check to only include a specific path if doing the multiple engines.
```ruby
config.before(:each, type: :decorator) do |example|
if …
```
=> Update README to show usage of Draper::ViewContext.controller in RSpec + Engine Apps

.gitignore, .travis.yml, CHANGELOG.md, Gemfile, README.md, Rakefile, draper.gemspec, gemfiles/4.0.gemfile, gemfiles/4.1.gemfile, gemfiles/4.2.gemfile, lib/draper.rb, lib/draper/decoratable.rb, lib/draper/decorator.rb, lib/draper/railtie.rb, lib/draper/tasks/test.rake, lib/draper/test/rspec_integration.rb, lib/draper/test_case.rb, lib/draper/view_context/build_strategy.rb, spec/draper/decoratable_spec.rb, spec/dummy/app/views/posts/_post.html.erb, spec/dummy/config/mongoid.yml, spec/dummy/spec/decorators/active_model_serializers_spec.rb, spec/dummy/spec/decorators/post_decorator_spec.rb, spec/dummy/spec/mailers/post_mailer_spec.rb, spec/dummy/spec/shared_examples/decoratable.rb, spec/dummy/test/decorators/minitest/view_context_test.rb, spec/dummy/test/decorators/test_unit/view_context_test.rb, spec/integration/integration_spec.rb, spec/performance/benchmark.rb, spec/spec_helper.rb
Note that for simplicity's sake, this PR drops support for Ruby < 2 and Rails < 5.
It also makes Active Model Serializers a runtime dependency. I'll try and undo that if I can.
=> Rails 5 compatibility

lib/draper/view_context/build_strategy.rb, spec/draper/view_context/build_strategy_spec.rb
Hi,
the latest rails 5.1 changed the "ActionController::TestRequest.create" method by adding one parameter.
https://github.com/rails/rails/pull/26092
so, with latest rails , I got:
```
actionpack/lib/action_controller/test_case.rb:38:in `create': wrong number of arguments (given 0, expected 1) (ArgumentError)
```
in order to keep updated with latest rails and compatible with current 5.0, I made this PR.
Hope it can help.
=> add compatibility with latest rails 5.1

lib/generators/rspec/templates/decorator_spec.rb
The default Rails spec generators should not use the monkey patched version of
describe. (https://github.com/rspec/rspec-rails/pull/1052)
=> Use non-monkey patch describe in generators.

lib/draper/decoratable.rb, spec/draper/decoratable_spec.rb
Rescue in .decorator_class falsely catches genuine NameError
Within `./draper_test.rb`:
```ruby
begin
require "bundler/inline"
rescue LoadError => e
$stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
raise e
end
gemfile(true) do
source "https://rubygems.org"
gem "rails"
gem "activemodel-serializers-xml"
gem "sqlite3"
gem "draper"
end
require "rails"
require "activemodel-serializers-xml"
require "draper"
require "minitest/autorun"
class DummyApp < Rails::Application
config.root = File.dirname(__FILE__)
config.autoload_paths << File.dirname(__FILE__)
config.session_store :cookie_store, key: "cookie_store_key"
secrets.secret_token    = "secret_token"
secrets.secret_key_base = "secret_key_base"
config.logger = Logger.new($stdout)
Rails.logger  = config.logger …
```
=> Fix wrong UninferrableDecoratorError error raising

lib/draper/undecorate.rb, spec/draper/undecorate_chain_spec.rb
Often I need method to fully undecorate object. For example, I want to get purely `baz` from `decorated_baz = FooDecorator.new(BarDecorator.new(baz))`.
=> Add undecorate_chain feature

CHANGELOG.md, lib/draper/view_context/build_strategy.rb
Fixed a bug where helpers were used inside a decorator and this decorator was used outside of controller context.
=> Bugfix for missing ActionController::TestRequest

spec/draper/view_context/build_strategy_spec.rb, spec/dummy/config/boot.rb, spec/dummy/fast_spec/post_decorator_spec.rb
This pull request fixes a couple deprecations. One of which will be removed in Rails 5.1.
The deprecations are:
DEPRECATION WARNING: Comparing equality between `ActionController::Parameters` and a `Hash` is deprecated and will be removed in Rails 5.1. Please only do comparisons between instances of `ActionController::Parameters`. If you need to compare to a hash, first convert it using `ActionController::Parameters#new`. (called from block (3 levels) in <module:Draper> at /Users/cliff/Code/drapergem/draper/spec/draper/view_context/build_strategy_spec.rb:42)
/Users/cliff/Code/drapergem/draper/spec/dummy/config/boot.rb:5: warning: File.exists? is a deprecated name, use File.exist? instead
Possible false positive in tests:
WARNING: Using the `raise_error` matcher without providing a specific …
=> Fix deprecations and possible false positive issue in tests.

lib/draper.rb, lib/draper/decorator.rb, spec/draper/decorator_spec.rb
Since source has been renamed to object, it is better for consistency to have UninferrableObjectError class name with the error message mentioning 'object' property instead of 'source'.
=> Rename UninferrableSourceError to UninferrableObjectError

lib/draper/collection_decorator.rb, lib/draper/helper_proxy.rb, lib/draper/test/devise_helper.rb, lib/draper/view_context.rb, spec/draper/collection_decorator_spec.rb, spec/dummy/spec/decorators/devise_spec.rb, spec/dummy/test/decorators/minitest/devise_test.rb, spec/dummy/test/decorators/test_unit/devise_test.rb
This pull request removes all functionality that was previously deprecated. This code was originally in [Support Rails::API controllers](https://github.com/drapergem/draper/pull/754), but I thought it would be best to pull it out into a separate pull request for better tracking.
=> Remove previously deprecated functionality.

lib/draper.rb, lib/draper/decorator.rb, spec/draper/decorator_spec.rb
Issue: https://github.com/drapergem/draper/issues/725
This pull request fixes the issue by removing the conflicting `source`, `to_source`, `source_class` and `source_class` aliases. It also renames some of the tests to keep the terminology consistent. In addition the aliases, the `UninferrableSourceError` was removed in favor of `UninferrableObjectError`.
Ultimately these changes should have been deprecated first, but we will document them in the changelog / release notes well to make up for it.
=> Issue 725: Remove conflicting source alias

lib/draper/railtie.rb
Initialize Draper's ViewContext when using the runner command in a
similar way to using the console command. Without this code run by the
rails runner command (e.g. when processing commands from a message
queue) will not have a properly initialized ViewContext, and
consequently the helpers will not be initialized.
=> Also initialize ViewContext for rails runner

README.md, lib/draper.rb, lib/draper/configuration.rb, lib/draper/railtie.rb, lib/draper/view_context/build_strategy.rb, spec/draper/configuration_spec.rb, spec/draper/view_context/build_strategy_spec.rb, spec/dummy/app/controllers/application_controller.rb, spec/dummy/app/controllers/base_controller.rb, spec/dummy/app/controllers/posts_controller.rb, spec/dummy/config/initializers/draper.rb, spec/dummy/spec/decorators/post_decorator_spec.rb, spec/spec_helper.rb
This pull request adds configuration to draper so that you can customize the default controller. According to the documentation in the README:
> ## Configuration
> Draper works out the box well, but also provides a hook for you to configure its 
> default functionality. For example, Draper assumes you have a base `ApplicationController`.
> If your base controller is named something different (e.g. `BaseController`),
> you can tell Draper to use it by adding the following to an initializer:
>
>```ruby
>Draper.configure do |config|
>  config.default_controller = BaseController
>end
>```
This also lays the ground work for other configuration options in the future. This work was originally inspired from the [#776](https://github.com/drapergem/draper/pull/776) by @nick-donald.
Issue …
=> Add support for custom default controller configuration

.github/PULL_REQUEST_TEMPLATE.md
This branch adds a Markdown document to be used as a template for GitHub pull request descriptions.  The template document will pre-fill into the PR description text editor, allowing the submitter to recognize and provide necessary information in a standard format.  This change will ease maintainers' ability to understand changes by collaborators, helping to streamline the flow of repository changes.
Unfortunately, this change will not be testable until it's in the master branch.  At that point, the `.github` directory will be recognized by GitHub which will allow future PRs to use the template.  Additional templates may be added to this directory in the future (see blog post reference link below).
N/A
* [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request …
=> GitHub pull request template

spec/dummy/test/decorators/minitest/view_context_test.rb
This pull request fixes the indeterminate test issue causing builds to fail randomly. I finally got to the bottom of what was causing it. The issue was with the minitest spec tests. A couple of the `describe` blocks didn't have the word "decorator" in them. This prevented minitest from registering the spec type as `Draper::TestCase`. Since the tests weren't registered as a `Draper::TestCase`, it wasn't including `Draper::TestCase::ViewContextTeardown` which defines `teardown` to clear the view context. Since the view context wasn't being cleared after these tests, the next test that called a helper on `ViewContext.current` blew up.
Once merged, we should not longer see builds fail randomly. You can test locally by:
1. `$ cd spec/dummy`
2. `SEED=8910 rake` should fail repeatedly on master. …
=> Fix the indeterminate test issue.

lib/draper/decoratable.rb, spec/draper/decoratable_spec.rb
Draper::Decorater provides the object method and we should delegate === to this
method only for these types.
Other classes could respond_to?(:object) so using is_a? clarifies not just any
class implementing object but only classes that are a Draper::Decorator.
Besides this, another major reason is is_a? is much faster than respond_to?
in ActiveRecord models because of the number of methods AR provides and the
layers of delegation. There is a cache specifically for respond_to? [1] because
it's so slow.
Even with this cache, some of our pages are 10% faster by using the is_a? change
from this patch.
The original implementation [2] used the method source, which was later renamed
to object.  The tests seem to indicate the intention was to always have
this === delegation to source/object for …
=> Only Draper::Decorator types should delegate === to object.

spec/draper/decorator_spec.rb, spec/spec_helper.rb
This branch un-skips a test and fixes the underlying reason for skipping it in the first place.  The culprit, a class definition `Other` in the `spec_helper`, was preventing this test from passing.  The build passes after removing this and the `skip` directive and does not affect other tests in the suite.
1. Run `rake`.
1. All specs should pass.
N/A
N/A
=> un-skip test and remove unused class definition

.codeclimate.yml, .rubocop.yml, draper.gemspec
This pull request adds Code Climate configuration for engine based analysis. It also adds Rubocop as a development dependency. Note, this will decrease our Code Climate score dramatically until we get around to fixing some of the style issues. We can disable certain rules entirely if people feel Code Climate / Rubocop is being too picky. My goal is to get Rubocop added to the rake task / continuous integration, but want to wait until we get a chance to address some of its complaints. 
The Code Climate results will show up once this pull request is merged into master. If you want to test rubocop, just bundle and run: `$ rubocop`.
None
* [GitHub Issue 783](https://github.com/drapergem/draper/issues/783)
=> Add rubocop development dependency and code climate configuration.

spec/draper/view_context/build_strategy_spec.rb, spec/dummy/app/controllers/posts_controller.rb
Because there is no hard constraint on Rails version, tests run against the newest version available. Rails 5.1 removes `to_h` from unpermitted parameters class. Using `empty?` is a sufficient replacement.
Also, Rails 5.1 does not accept `:text` option for `render`. Using `:html` should do a job.
```
rspec ./spec/draper/view_context/build_strategy_spec.rb:33
RAILS_ENV=development rspec spec/integration/integration_spec.rb
```
=> Fix failing specs re Rails 5.1

lib/draper/collection_decorator.rb, spec/draper/collection_decorator_spec.rb
I'm reverting this pull request for the time being. It was just a performance optimization to begin with. It caused some issues as noted [in this thread](https://github.com/drapergem/draper/commit/f6a7b17a8acfa7633762d665ab218a6478d32a98). Furthermore, running the benchmarks again are returning inconsistent results. This time around, it's showing the performance being slightly better pre-patch. I'm not sure if this is just do to inconsistencies on my machine or what. Either way, I think this is the safest bet until we can resolve the issues noted above and provide convincing benchmarks.
=> Revert "Optimization: Optimize CollectionDecorator Enumerable behavior"

lib/draper/view_context.rb, spec/draper/view_context_spec.rb
When we reassign controller it is the right thing to do to clear current view context stored in request store. Consider a case when view context was built before the request was made (usage of `h` helper in class level context). View context is built from default controller and has no information about the request. During first request `Draper::ViewContext.current.controller` will be different than `Draper::ViewContext.controller`.
Example Rails app. Use `h.content_tag` in class context of some decorator, make this class be eagerly loaded.
Perform some request that will execute some decorator to refer to e.g. `request.env` values that are set up by some middleware (e.g. warden manager).
See that `env` is missing that key.
With that fix, view_context is regenerated when a controller is …
=> Clean view context when controller changes

Guardfile, lib/draper/tasks/test.rake, lib/generators/mini_test/decorator_generator.rb, spec/dummy/db/schema.rb, spec/dummy/lib/tasks/test.rake
Full replacement of rocket hash syntax with newer, because of rocket hash deprecation.
=> Replace hash rockets with new syntax

CHANGELOG.md, README.md, lib/draper/version.rb
Contains version bump for release 3.0.0. The changelog could use more details if there are some.
=> Release 3.0.0

spec/dummy/db/migrate/20121019115657_create_posts.rb
Rails 5.1 has version number in migrations.
=> Add migration version to create posts migration from dummy app in spec

lib/generators/draper/install_generator.rb, lib/generators/mini_test/decorator_generator.rb, lib/generators/rails/decorator_generator.rb, lib/generators/rspec/decorator_generator.rb, lib/generators/test_unit/decorator_generator.rb
Refactored generators:
1. Add `check_class_collision suffix: "DecoratorTest"` to generator for TestUnit
2. Nested namespace `Generators` same as originals ([test_unit](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/test_unit.rb#L4), [rspec](https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec.rb#L9)]
I've checked running on rails application for sandbox. No problems.
=> Refactor generator for TestUnit, RSpec

README.md, lib/draper/compatibility/global_id.rb, lib/draper/decorator.rb, spec/dummy/app/jobs/publish_post_job.rb, spec/dummy/config/environments/test.rb, spec/dummy/spec/jobs/publish_post_job_spec.rb, spec/dummy/spec/models/post_spec.rb
This pull request makes it so that decorators implement `GlobalID` so they can be passed to background jobs. While you can now pass a decorated object to a background job, it won't be decorated when it is deserialized. This may lead to some confusion, so it is documented in the README.
Try to pass a decorated object to a background job and it should no longer throw `ActiveJob::SerializationError`.
* [GitHub Issue 663](https://github.com/drapergem/draper/issues/663)
* [GitHub Pull Request #669 containing initial documentation](https://github.com/drapergem/draper/pull/669)
=> Feature: ActiveJob Integration and Documentation

lib/draper/decoratable.rb, lib/draper/decorator.rb, spec/draper/decoratable_spec.rb, spec/draper/decorator_spec.rb
Since Rails 5, draper gem gets some issues of raising `NameError` on inferring decorator class (https://github.com/drapergem/draper/issues/773). The previous PR (https://github.com/drapergem/draper/pull/795) fixes this issue when using `decorate_collection`, but this issue can also happen when using `decorate`, and we encountered this issue on our production code when upgrading to Rails 5.
I tried to replace `constantize` with `safe_constantize` in this PR, so we don't need to rescue and check if the `NameError` was caused by draper itself anymore. It should be safer than previous approach.
Thanks.
* [GitHub Issue #773 ](https://github.com/drapergem/draper/issues/773)
* [GitHub Pull Request #795 ](https://github.com/drapergem/draper/pull/795)
=> Let decorator_class infer anonymous class' decorator from superclass

lib/draper/decoratable.rb, spec/draper/decoratable_spec.rb, spec/spec_helper.rb
Thanks for the work on Draper to all the maintainers 👍
This provides a fix for #819 
When decorating an object without decorator, then the last class which was checked for a decorator is contained in the error message. In case of Rails this is most often `ActiveRecord::Base`.
This is a bit misleading and it would be better if the class which was actually tried to decorate is shown in the error message.
This is caused by the recursive nature of the `decorate` method which moves up  the hierarchy when no decorator class found. And raises when it can not move further up.
Before:
```ruby
Something::Bar.decorate
Draper::UninferrableDecoratorError: Could not infer a decorator for ActiveRecord::Base.
```
After:
```ruby
Something::Bar.decorate
Draper::UninferrableDecoratorError: Could not infer a …
```
=> When decoration fails, show original class

draper.gemspec
The current gemspec restricts Draper to Rails versions no higher than 5.x.
This change to the gemspec allows any versions including or greater than 5.x, and as such allows Draper to be used with Rails 6.
I'm using this branch against an actively developed project which we're now developing against Rails 6 with no issues so far.
Existing tests should suffice as there are no changes in Rails 6 which should affect Draper.
=> Rails 6 Support

spec/draper/decoratable_spec.rb
Indent of `end` is different from that of accompanying `it` clause.
So I fixed it.
=> Fix indent

README.md
This pull request adds documentation for fixing the view context leakage between specs. I wanted to start with a documentation fix and go from there. If we later determine we need to clear the view context for all spec types by default, we can remove this documentation. See the referenced issue for the complete history of the issue.
N/A
None
* [Should automatically clear view_context before/after each spec](https://github.com/drapergem/draper/issues/814)
=> Document the fix for view context leaking in specs.

lib/draper/query_methods.rb, spec/draper/query_methods_spec.rb
1. Create a decorator for the model and its association
```ruby
class OrderHistoryDecorator < Draper::Decorator
delegate_all
end
class OrderDecorator < Draper::Decorator
delegate_all
decorates_association :order_histories, with: OrderHistoryDecorator
end
```
2. Call `respond_to?` with some ORM method allowed by the strategy
```ruby
[1] pry(main)> order.order_histories.decorate.respond_to?(:includes)
=> true
```
* method_missing [usage](https://thoughtbot.com/blog/always-define-respond-to-missing-when-overriding)
=> fix: Make CollectionDecorator respond_to? to ORM methods

.travis.yml, README.md, draper.gemspec, spec/draper/draper_spec.rb, spec/generators/controller/controller_generator_spec.rb, spec/integration/integration_spec.rb, spec/spec_helper.rb
Add `simplecov` now become simpler, as it now support merging results for multiple test suites.
* [SimpleCov Readme of Merging Results](https://github.com/colszowka/simplecov#merging-results)
* [Deprecated Pull Request](https://github.com/drapergem/draper/pull/769)
=> Add SimpleCov for code coverage analysis

lib/draper/automatic_delegation.rb, spec/draper/decorator_spec.rb
Public methods defined on the object was being delegated to the decorator even though it was overridden by a private method.
1. Create a simple PORO with a public method
```ruby
class Job
def location
Struct.new(:id) { }
end
end
```
1. Create a decorator and override the public method with a private
```ruby
class JobDecorator < Draper::Decorator
delegate_all
private
def location
LocationDecorator.new(object.location)
end
end
```
3. It should raise an exception when calling `.location` from the decorator
```ruby
[9] pry(main)> JobDecorator.decorate(Job.new).location
NoMethodError: private method `location' called for #<JobDecorator:0x0000559f113ba118>
```
* Issue #771
=> fix: Don't delegate public methods overridden by a private in the decorator

README.md
Current README example for stubbing in Rspec is both deprecated and does not work in a default Rspec install. 
In rspec 3, if you try:
helpers.stub(users_path: '/users')
You get a deprecation warning:
Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead.
And in addition to the deprecation warning, it actually fails with a message:
#<Draper::HelperProxy: ...  [lots of text] ... does not implement: users_path
If we switch to 'new' rspec API `allow(:helpers).to receive(:users_path).and_return("/users")`, we don't get the deprecation method, but still get the failure with same error message.
If we additionally wrap in `without_partial_double_verification` [introduced in …
=> Use current rspec API for rspec stub example in README

lib/draper/query_methods.rb, spec/draper/query_methods_spec.rb
* [GitHub Issue #864](https://github.com/drapergem/draper/issues/864)
The context given to a Collection Decorator was being lost when an `ActiveRecord::QueryMethod` was being called on a `Draper::CollectionDecorator`.
E.g. 
```rb
decorated_collection = PostDecorator.decorate_collection(Post.all, context: {user: "foo"}).order("created_at asc")
decorated_collection.context #{}
decorated_collection.decorator_class #nil
```
This was happening because `method_missing` on `draper/lib/draper/query_methods.rb` is invoking ActiveRecord method with `send` and creating another instance of decorator to decorate the result.
```draper/lib/draper/query_methods.rb
def method_missing(method, *args, &block) 
return super unless strategy.allowed? method 
object.send(method, *args, &block).decorate 
end 
``` …
=> Add preservation of decorator options on QueryMethods

Gemfile, lib/draper/view_context/build_strategy.rb, spec/dummy/app/controllers/application_controller.rb
In Rails 6.0 the API for `ActionView::Base.new` is changing.
`ActionView::Base.new` now take arguments [1], otherwise you
will see the following deprecation warning:
```
DEPRECATION WARNING: ActionView::Base instances should be constructed with a lookup context, assignments, and a controller.
```
[1] https://github.com/rails/rails/commit/e17fe52e0e0ef0842b6c409e1110a862c4e005bc
`ViewContext::BuildStrategy::Fast` does not have lookup context, so use `empty`
method instead of `new` to build instance.
I'm not sure test policy, so I did not update Rails version of test. But if need, I will update that to 6.0.
=> Add support for Rails 6.0 to `ViewContext::BuildStrategy`

lib/draper/delegation.rb
Remove ruby 2.7 deprecation
```
lib/ruby/gems/2.7.0/gems/draper-3.1.0/lib/draper/delegation.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
Detail your changes here.  
A few sentences describing the overall goals of the pull request's commits will suffice.
Some questions you might answer:
* [GitHub Issue 869](https://github.com/drapergem/draper/issues/869)
=> Remove ruby 2.7 deprecation

lib/draper/automatic_delegation.rb, spec/draper/decorator_spec.rb
https://github.com/drapergem/draper/pull/849 introduced a valid fix to prevent calling object's public method when a decorator overwrites it through a private one. There is one caveat, though. `private_methods` methods has `all` parameter set to `true` by default (https://ruby-doc.org/core-2.7.0/Object.html#method-i-private_methods). As a result all private methods are returned, instead of only the ones defined on the object.
This commit fixes the above issue by setting the `all` parameter to `false`.
```ruby
class Job
def fork
Struct.new(:id) { }
end
end
class JobDecorator < Draper::Decorator
delegate_all
end
```
```ruby
JobDecorator.decorate(Job.new).fork
```
gives:
```
NoMethodError: private method `fork' called for #<JobDecorator:0x00007fb73ca977e8>
```
even though `fork` method is …
=> fix: Check only object's private method when preventing delegation

lib/draper/compatibility/api_only.rb
this is missing to change in past pull request. https://github.com/drapergem/draper/pull/852
other changes
```
alias_method :decorate, :new => alias :decorate :new
```
missing changes
```
alias :previous_render_to_body :render_to_body => alias_method :previous_render_to_body, :render_to_body
```
reference: https://github.com/drapergem/draper/pull/852/files#diff-1ca405441e9eec709668800446ec14c2R17
=> fix alias method

spec/draper/collection_decorator_spec.rb, spec/draper/decorator_spec.rb
**When running tests**, there were fixable warnings emitted:
```
/Users/olle/opensource/draper/spec/draper/collection_decorator_spec.rb:220: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/olle/opensource/draper/spec/draper/decorator_spec.rb:442: warning: ambiguous first argument; put parentheses or a space even after `/' operator
```
Solution: **add parentheses** to disambiguate.
1. Observe that test output (with `RUBYOPT=-W2`) does not contain the above warnings.
=> Avoid Ruby warnings "ambiguous first argument"

.github/workflows/ci.yml
This adds the mongo service back into the GitHub actions configuration from #893.
The two failing tests in here should be fixed by #895.
=> Add mongo service to Github Actions

Gemfile, draper.gemspec, spec/draper/collection_decorator_spec.rb, spec/dummy/config/environments/development.rb, spec/dummy/config/environments/production.rb, spec/dummy/config/environments/test.rb, spec/dummy/config/storage.yml, spec/generators/decorator/decorator_generator_spec.rb
Draper::CollectionDecorator#{is_a?,kind_of?} triggers
decorating the object. When stubbing a method call
on a CollectionDecorator, RSpec itself will call #is_a?
on the object. See:
https://github.com/rspec/rspec-mocks/blob/ea4d8ea4532480500462cc7a633d3408656a4dcd/lib/rspec/mocks/proxy.rb#L38
That's why the object will always be decorated when
stubbing a method on it.
We can circumvent this issue by directly checking
the definition of @decorated_collection.
Edit:
This PR got bigger than intended, but it fixes more failing and flaky specs.
=> Fix decoration spec

draper.gemspec, spec/draper/decorator_spec.rb
The `rake` executable in the `rake` gem is being loaded, but it's also present in other gems (draper).
Draoer doesn't provide any executable, and if it did, it should go in 'exe' dir.
Fix this warning in [CI](https://github.com/drapergem/draper/runs/1704069353?check_suite_focus=true#step:7:9) : 
```sh
The `rake` executable in the `rake` gem is being loaded, but it's also present in other gems (draper).
If you meant to run the executable for another gem, make sure you use a project specific binstub (`bundle binstub <gem_name>`).
If you plan to use multiple conflicting executables, generate binstubs for them and disambiguate their names.
```
=> Fix Rake warning in CI

.github/workflows/ci.yml, draper.gemspec, lib/draper.rb, lib/draper/automatic_delegation.rb, lib/draper/helper_proxy.rb, lib/draper/lazy_helpers.rb, lib/draper/query_methods.rb, lib/draper/view_helpers.rb
Fix kwargs for Ruby 2.7.
- [Separation of positional and keyword arguments in Ruby 3.0](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)
=> Fix kwargs for Ruby 2.7

README.md
This PR is the follow-up to #893.
In #893, CI is migrated from Travis CI to GitHub Actions.
This patch replaces the Travis CI badge in README with the GitHub Actions one.
=> Replace the Travis CI status badge with the GitHub Actions one

Gemfile
Latest mongoid only supports Ruby >= 2.5
Ref: https://github.com/mongodb/mongoid/pull/5058
=> Fix broken CI

.github/workflows/ci.yml, Gemfile, spec/draper/decoratable_spec.rb, spec/draper/decorator_spec.rb, spec/draper/factory_spec.rb
This PR adds Ruby 3.1 and 3.2 to the CI matrix, and fix CI failure in Ruby 3.
Here are the details:
- **Address CI failure in Ruby 3**
Since [rspec-mocks v3.10.3](https://github.com/rspec/rspec-mocks/blob/main/Changelog.md#3103--2022-01-28), `with` now distinguishes between keyword args and hash in Ruby 3.
See rspec/rspec-mocks#1394 for details.
- **Enable bundler-cache in ruby/setup-ruby**
This reduces code for caching.
- **Add Ruby 3.1 and 3.2 to the CI matrix**
`net-imap`, `net-pop` and `net-smtp` are bundled gems in Ruby 3.1.
So they need to be listed in `Gemfile`.
See https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/ for details.
- **Bump `actions/checkout` from v2 to v3**
- **Add GitHub token permissions for workflow**
GitHub asks developers to define workflow …
=> Add Ruby 3.1 and 3.2 to the CI matrix and fix CI failure in Ruby 3

spec/performance/benchmark.rb
The alias `File.exists?` was removed in Ruby 3.2:
* https://bugs.ruby-lang.org/issues/17391
* https://rubyreferences.github.io/rubychanges/3.2.html#removals
`File.exist?` has been in Ruby since at least 1.8: https://ruby-doc.org/core-1.8.6/File.html#method-c-exist-3F
=> Replace deprecated/removed `File.exists?` alias

draper.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/draper or some tools or APIs that use the gem's metadata.
=> Use https for GitHub link

README.md
I added information about generator settings to the README because it was missing.
=> Update README with config to disable generation of decorator files

lib/draper/query_methods.rb, spec/draper/query_methods_spec.rb
`Draper::Collection#respond_to?` does not work properly when using a non AR object, eg:
```ruby
class FooDecorator < Draper::Decorator; end  
decorator_collection = FooDecorator.decorate_collection([Object.new])
decorator_collection.respond_to?(:limit) #=> true
decorator_collection.limit(10) # Raises NoMethodError: undefined method `limit' for []:Array   
```
I think `decorator_collection.respond_to?(:limit)` should return `false` for these cases
1. Create a empty decorator with: `class FooDecorator < Draper::Decorator; end `
2. Initialize a non AR collection with it: `decorator_collection = FooDecorator.decorate_collection([Object.new])`
3. `decorator_collection.respond_to?(:limit)` should return `false`
* [GitHub Issue ####](https://github.com/drapergem/draper/issues/####)
* [GitHub …
=> Fix CollectionDecorator#respond_to? for non AR collections

lib/draper/view_context/build_strategy.rb, spec/draper/view_context/build_strategy_spec.rb
Replace `ActionController::TestRequest` with `ActionDispatch::TestRequest`
because
1) soft deprecated
2) will cause very hard to predict/test failures with ActiveJob/Sidekiq/Rake tasks. see #926 
The current PR also drops support for rails < 6.0 
I think this is a good idea (especially as the tests that were dropped were written from a Rails 5.0 perspective, so are very outdated, and brittle) but open to discussion around this if there's any engagement on this PR.
See #926 
* [GitHub Issue 926](https://github.com/drapergem/draper/issues926)
fixes #926
=> fix issue with using draper outside of controller/view context

README.md, lib/draper/compatibility/global_id.rb, spec/dummy/spec/decorators/post_decorator_spec.rb, spec/dummy/spec/jobs/publish_post_job_spec.rb, spec/dummy/spec/models/post_spec.rb
Implementing `Decorator.find` improves compatibility with Global ID and allows one to use decorated objects in background jobs seamlessly.
1. Decorate an object.
2. Serialize the decorated object with Global ID or pass it to a job.
3. Deserialize the object.
4. Check if it's the same one and is still decorated.
* Resolves [#663](https://github.com/drapergem/draper/issues/663)
* Improves [#817](https://github.com/drapergem/draper/pull/817)
=> Improved integration with Global ID

Gemfile, lib/draper/compatibility/broadcastable.rb, lib/draper/decoratable.rb, spec/dummy/app/models/post.rb, spec/dummy/config/application.rb, spec/dummy/config/cable.yml, spec/dummy/spec/models/post_spec.rb
Overriding defaults for Turbo broadcast jobs allows one to get decorated objects in model partials by default.
1. Broadcast an object with Turbo.
2. Check if the local variable passed into the partial is decorated.
* Resolves [#910](https://github.com/drapergem/draper/issues/910)
* Depends on [#928](https://github.com/drapergem/draper/pull/928)
=> Integration with `Turbo::Broadcastable`

lib/draper/automatic_delegation.rb
Currently, `delegatable?` call `private_methods` to check method is private or not. The `private_methods` generates an Array of methods per call. So a method call via `delegate_all` generates an extra Array every time.
This patch use `private_method_defined?` instead of `private_methods`. This reduce the extra Array.
The inherit argument for `private_method_defined?` is supported since Ruby 2.6.
So this patch only works for >= Ruby 2.6. Rubies old than Ruby 2.6 keep using `private_methods`.
Ref: https://bugs.ruby-lang.org/issues/14944
Benchmark is here.
```ruby
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
gem "activerecord"
gem "sqlite3"
if ENV["USE_FORKED_GEM"]
gem "draper", github: "y-yagi/draper", branch: "improve-delegate_all-performance"
else
gem "draper" …
```
=> Improve performance of method call via `delegate_all`

draper.gemspec, lib/draper.rb, lib/draper/decoratable.rb, lib/draper/decoratable/collection_proxy.rb, lib/draper/railtie.rb, spec/dummy/app/decorators/comment_decorator.rb, spec/dummy/app/models/comment.rb, spec/dummy/app/models/post.rb, spec/dummy/db/migrate/20240907041839_create_comments.rb, spec/dummy/db/schema.rb, spec/dummy/spec/models/post_spec.rb, spec/dummy/spec/spec_helper.rb
`ActiveRecord::Associations::CollectionProxy#decorate` ignores `target` (be it already loaded or not) and loads the association again every time it's called.
That's why unsaved records get missing from the decorated collection.
* `it 'returns a decorated collection'`
1. Ensure a record and some records associated with it are persisted.
2. Get the decorated association: `record.associated_records.decorate`.
3. Ensure that it matches `record.associated_records`.
* `it 'uses cached records'`
1. Ensure a record and some records associated with it are persisted.
2. Get the association: `record.associated_records`.
3. Get the decorated association: `record.associated_records.decorate`.
4. Ensure the association was loaded only once.
* `it 'caches records'`
1. Ensure a record and some records …
=> Associations: `#decorate` queries DB every time

.github/workflows/ci.yml, Gemfile, draper.gemspec
* Ruby 2.6 (see hotwired/turbo-rails/issues/681).
* Moved Rails versions to CI `matrix`.
* Both edge and outdated Ruby / Rails versions may fail.
* Use the latest RubyGems.
=> Workflows / CI: fixed & refactored

.github/workflows/ci.yml
Rails 8.0 has been released. I would like to confirm whether `draper` works well with it.
=> CI against Rails 8.0

.github/workflows/ci.yml
Ubuntu-latest workflows use Ubuntu-24.04 image now.
https://github.com/actions/runner-images/issues/10636
But, it seems that old sqlite3 gem(for Ruby 2.4) doesn't work with it.
https://github.com/drapergem/draper/actions/runs/12762245525/job/35570471534?pr=940
So I fixed it to use Ubuntu 22.04. It may be better to use Ubuntu 22.04 only for Ruby 2.4.  But, it would be complex. 
Ubuntu 22.04 will be supported by Apr 2027. So it's OK to keep using it so far(And we should drop old Ruby versions before that).
=> Use Ubuntu 22.04 image to fix broken Ruby 2.4 build

.github/workflows/ci.yml, spec/draper/decorator_spec.rb
Ruby 3.4 has been released. I would like to add Ruby 3.4 to CI to confirm whether `draper` works well with it.
=> CI against Ruby 3.4

CHANGELOG.md, lib/draper/version.rb
Fixes https://github.com/drapergem/draper/issues/941#issuecomment-2617490431
I've pushed the updated version to the `v4.0.4` git tag. You can see the diff here: https://github.com/drapergem/draper/compare/v4.0.3...v4.0.4
I'll hold off on publishing it to rubygems until this PR is approved.
=> Release version 4.0.4, update changelog

draper.gemspec
The `.gemspec` file to optimize the gem package size and structure. The changes include:
- Modified `files` to exclude test files, Gemfile, and CI related files from the package.
- Removed the deprecated `test_files` specification as it is no longer recommended.
These changes reduce the extracted package size from from 1.1MB to 340KB.
Benefits:
- Shorter download times for users
- Reduced container sizes when the gem is included
- https://github.com/rubygems/guides/issues/90
- https://github.com/rubygems/bundler/pull/3207
- [Template for the *.gemspec file generated by bundle gem command](https://github.com/rubygems/rubygems/blob/bundler-v2.6.5/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt)
=> Remove unused files from package

spec/dummy/spec/rails_helper.rb
This wraps each example in a transaction that's rolled back at the end of the example to avoid records leaking from one test to the next.
Without this, if you repeatedly run tests, your database will repeatedly grow, and depending on your assertions, may fail due to data from previous test runs.
CI wouldn't have surfaced this issue as it creates a new DB for each run.
=> Enable transactional fixtures in dummy app's specs
